cart/urls.py
from django.urls import path, include

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('api/', include('cart.api_urls'))
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order-create'),
    path('detail/<int:order_id>/', views.order_detail, name='order-detail'),
    path('list/', views.order_list, name='order-list'),
    path('<int:order_id>/', views.order_finalize, name='order-finalize'),
    path('payment/<int:order_id>/<price>/', views.payment, name='order-payment'),
    path('verify/', views.verify, name='order-verify'),
    path('apply/<int:order_id>/', views.coupon_apply, name='order-coupon-apply'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('oders/', include('orders.urls')),
    path('', include('shopping.urls')),
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
from django.core.exceptions import ValidationError


class CartAddForm(forms.Form):
	quantity = forms.IntegerField(label='تعداد', min_value=1)

	def __init__(self, *args, **kwargs):
		self.product = kwargs.pop('product', None)
		super(CartAddForm, self).__init__(*args, **kwargs)

	def clean_quantity(self):
		quantity = self.cleaned_data.get('quantity')
		if quantity > self.product.quantity:
			raise ValidationError(f'حداکثر تعداد قبال سفارش از این کالا {self.product.quantity} عدد می‌باشد')
		return quantity

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST

from .cart_session import Cart
from .forms import CartAddForm
from shopping.models import Product


def cart_detail(request):
    cart = Cart(request)
    context = {
        'cart': cart
    }
    return render(request, 'cart/cart_detail.html', context=context)


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddForm(request.POST, product=product)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'])
        return redirect('cart:cart_detail')
    else:
        context = {
            'product': product,
            'form': form
        }
        return render(request, 'shopping/product_detail.html', context=context)


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')

cart/templates/cart/cart_detail.html
{% extends 'layout.html' %}

{% block content %}

<table class="table table-dark">
    <thead>
    <tr>
        <th scope="col">شماره</th>
        <th scope="col">کالا</th>
        <th scope="col">تعداد</th>
        <th scope="col">قیمت واحد</th>
        <th scope="col">قیمت کل</th>
        <th scope="col">حذف</th>
    </tr>
    </thead>
    <tbody>
    {% for item in cart %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td>{{ item.product }}</td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.total_price }}</td>
        <td><a href="{% url 'cart:cart_remove' item.product.id %}">حذف</a></td>
    </tr>
    {% endfor %}
    <tr>
        <td colspan="4"></td>
        <td>جمع کل</td>
        <td>{{ cart.get_total_price }} تومان</td>
    </tr>
    </tbody>
</table>

    <a href="{% url 'orders:order-create' %}" class="btn btn-primary">نهایی‌کردن خرید</a>

{% endblock %}