cart/urls.py
from django.urls import path, include

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('api/', include('cart.api_urls'))
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order-create'),
    path('detail/<int:order_id>/', views.order_detail, name='order-detail'),
    path('list/', views.order_list, name='order-list'),
    path('<int:order_id>/', views.order_finalize, name='order-finalize'),
    path('payment/<int:order_id>/<price>/', views.payment, name='order-payment'),
    path('verify/', views.verify, name='order-verify'),
    path('apply/<int:order_id>/', views.coupon_apply, name='order-coupon-apply'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('oders/', include('orders.urls')),
    path('', include('shopping.urls')),
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/models.py
from django.db import models
from django.conf import settings
from shopping.models import Product
from django.core.validators import MinValueValidator, MaxValueValidator


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='orders')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    discount = models.IntegerField(blank=True, null=True, default=None)
    
    class Meta:
        ordering = ('-created',)
        verbose_name = 'سفارش'
        verbose_name_plural = 'سفارش‌ها'

    def __str__(self):
        return f'{self.user} - {str(self.id)}'

    def get_total_price(self):
        total = sum(item.get_cost() for item in self.items.all())
        if self.discount:
            discount_price = (self.discount / 100) * total
            return int(total - discount_price)
        return total

    def update_database(self):
        for item in self.items.all():
            item.update_database()


class OrderItem(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='items')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='order_items')
    price = models.IntegerField()
    quantity = models.PositiveSmallIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

    def update_database(self):
        self.product.update_quantity(sold_quantity=self.quantity)


class Coupon(models.Model):
    code = models.CharField(max_length=30, unique=True)
    valid_from = models.DateTimeField()
    valid_to = models.DateTimeField()
    discount = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    active = models.BooleanField(default=False)

    class Meta:
        verbose_name = 'کد تخفیف'
        verbose_name_plural = 'کدهای تخفیف'

    def __str__(self):
        return self.code

orders/forms.py
from django import forms


class CouponForm(forms.Form):
    code = forms.CharField(label='کد تخفیف')

orders/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Order, OrderItem, Coupon
from cart.cart_session import Cart
from suds.client import Client
from django.http import HttpResponse
from django.contrib import messages
from .forms import CouponForm
from django.views.decorators.http import require_POST
from django.utils import timezone


@login_required
def order_finalize(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    form = CouponForm()
    context = {
        'order': order,
        'form': form
    }
    return render(request, 'orders/order.html', context=context)


@login_required
def order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    context = {
        'order': order,
    }
    return render(request, 'orders/order_detail.html', context=context)


@login_required
def order_list(request):
    orders = request.user.orders.all()
    context = {
        'orders': orders,
    }
    return render(request, 'orders/order_list.html', context=context)


@login_required
def order_create(request):
    cart = Cart(request)
    order = Order.objects.create(user=request.user)
    for item in cart:
        OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
    cart.clear()
    return redirect('orders:order-finalize', order.id)


# MERCHANT = 'XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX'
# client = Client('https://www.zarinpal.com/pg/services/WebGate/wsdl')
# description = "پرداخت فروشگاه آنلاین"
# mobile = '09123456789'
# CallbackURL = 'http://localhost:8000/orders/verify/'


@login_required
def payment(request, order_id, price):
    global amount, o_id
    amount = price
    o_id = order_id
    result = request.GET.get('Status')
    response = redirect('orders:order-verify')
    response['Location'] += f'?Status={result}'
    return response
    # result = client.service.PaymentRequest(MERCHANT, amount, description, request.user.email, mobile, CallbackURL)
    # result = client.service.PaymentRequest(MERCHANT, amount, description, request.user.email, mobile, CallbackURL)
    # if result.Status == 100:
    #     return redirect('https://www.zarinpal.com/pg/StartPay/' + str(result.Authority))
    # else:
    #     return HttpResponse('Error code: ' + str(result.Status))


@login_required
def verify(request):
    print(request.GET)
    if request.GET.get('Status') == 'OK':
        # result = client.service.PaymentVerification(MERCHANT, request.GET['Authority'], amount)
        # if result.Status == 100:
        order = Order.objects.get(id=o_id)
        order.paid = True
        order.update_database()
        order.save()
        messages.success(request, 'تراکنش با موفقیت انجام شد', 'success')
        return redirect('shopping:home')
        # elif result.Status == 101:
        #     return HttpResponse('Transaction submitted')
        # else:
        #     return HttpResponse('تراکنش ناموفق بود')
    else:
        messages.error(request, 'تراکنش ناموفق بود یا توسط کاربر لغو شد', 'danger')
        return redirect('shopping:home')


@require_POST
def coupon_apply(request, order_id):
    now = timezone.now()
    form = CouponForm(request.POST)
    if form.is_valid():
        code = form.cleaned_data['code']
        try:
            coupon = Coupon.objects.get(code__exact=code, valid_from__lte=now, valid_to__gte=now, active=True)
        except Coupon.DoesNotExist:
            messages.error(request, 'کد تخفیف یافت نشد', 'danger')
            return redirect('orders:order-finalize', order_id)
        order = Order.objects.get(id=order_id)
        order.discount = coupon.discount
        order.save()
    return redirect('orders:order-finalize', order_id)

orders/templates/orders/order.html
{% extends 'layout.html' %}

{% block content %}
    <h3>نهایی‌کردن خرید</h3>

    <br/>

    <p>قابل پرداخت:
        {{ order.get_total_price }}
        تومان
    </p>

    <br/>

    <form action="{% url 'orders:order-coupon-apply' order.id %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="اعمال کد تخفیف">
    </form>

    <br/>

    <form action="{% url 'orders:order-payment' order.id order.get_total_price %}" method="get">
        <p><label>موفق باشه؟:<input type="checkbox" name="Status" value="OK" class="checkbox"/></label></p>
        <input type="submit" value="پرداخت" class="btn btn-danger">
    </form>
{#    <a href="{% url 'orders:order-payment' order.id order.get_total_price %}" class="btn btn-primary">پرداخت</a>#}

{% endblock %}

orders/templates/orders/order_detail.html
{% extends 'layout.html' %}

{% block content %}

<table class="table table-light">
    <thead>
    <tr>
        <th scope="col">شماره</th>
        <th scope="col">کالا</th>
        <th scope="col">تعداد</th>
        <th scope="col">قیمت واحد</th>
        <th scope="col">قیمت کل</th>
        <th scope="col">حذف</th>
    </tr>
    </thead>
    <tbody>
    {% for item in order.items.all %}
    <tr>
        <th scope="row">{{ forloop.counter }}</th>
        <td><a class="text-muted" href="{{ item.product.get_absolute_url }}">{{ item.product }}</a></td>
        <td>{{ item.quantity }}</td>
        <td>{{ item.price }}</td>
        <td>{{ item.get_cost }}</td>
{#        <td><a href="{% url 'cart:cart_remove' item.product.id %}">حذف</a></td>#}
    </tr>
    {% endfor %}
    <tr>
        <td colspan="4"></td>
        <td>جمع کل</td>
        <td>{{ order.get_total_price }} تومان</td>
    </tr>
    </tbody>
</table>
    {% if order.paid is False%}
        <a href="{% url 'orders:order-finalize' order.id %}" class="btn btn-primary">نهایی‌کردن خرید</a>
    {% endif %}
{% endblock %}

orders/templates/orders/order_list.html
{% extends 'layout.html' %}

{% block content %}

<table class="table table-light">
    <thead>
    <tr>
        <th scope="col">شماره</th>
        <th scope="col">تاریخ ایجاد</th>
        <th scope="col">آخرین ویرایش</th>
        <th scope="col">قیمت کل</th>
        <th scope="col">وضعیت پرداخت</th>
    </tr>
    </thead>
    <tbody>
        {% for order in orders %}
            <tr>
                <th scope="row">
                    <a href="{% url "orders:order-detail" order.id %}">
                        {{ forloop.counter }}
                    </a>
                </th>
                <td>{{ order.created }}</td>
                <td>{{ order.updated }}</td>
                <td>{{ order.get_total_price }}</td>
                <td>
                    {% if order.paid is True %}
                    موفق
                    {% else %}
                    ناموفق
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}