cart/urls.py
from django.urls import path, include

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('api/', include('cart.api_urls'))
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('oders/', include('orders.urls')),
    path('', include('shopping.urls')),
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.urls import path, re_path, include

from . import views

from .api_url import router


app_name = 'shopping'
urlpatterns = [
	path('', views.home, name='home'),
	re_path(r'category/(?P<slug>[-\w]+)/', views.home, name='category_filter'),
	re_path(r'detail/(?P<slug>[-\w]+)/', views.product_detail, name='product_detail'),
	path('api/',include(router.urls))
]

shopping/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):
    sub_category = models.ForeignKey('self', verbose_name='زیرشاخه‌ها', on_delete=models.CASCADE,
                                     related_name='subcategory', null=True, blank=True)
    is_sub = models.BooleanField(verbose_name='زیرشاخه', default=False)
    name = models.CharField(verbose_name='نام', max_length=200)
    slug = models.SlugField(verbose_name='اسلاگ', max_length=200, unique=True, allow_unicode=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'دسته‌بندی'
        verbose_name_plural = 'دسته‌بندی‌ها'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shopping:category_filter', args=[self.slug, ])


class Product(models.Model):
    category = models.ManyToManyField(Category, related_name='products', verbose_name='دسته‌بندی',)
    name = models.CharField(verbose_name='نام', max_length=200)
    slug = models.SlugField(verbose_name='اسلاگ', max_length=200, unique=True, allow_unicode=True)
    image = models.ImageField(verbose_name='تصویر', upload_to='products/%Y/%m/%d/')
    description = models.TextField(verbose_name='توضیحات')
    price = models.IntegerField(verbose_name='قیمت')
    available = models.BooleanField(verbose_name='موجود', default=True)
    created = models.DateTimeField(verbose_name='تاریخ اضافه شدن', auto_now_add=True)
    updated = models.DateTimeField(verbose_name='آخرین تغییر', auto_now=True)
    quantity = models.IntegerField(verbose_name=' تعداد موجودی', default=0)

    class Meta:
        ordering = ('name',)
        verbose_name = 'کالا'
        verbose_name_plural = 'کالاها'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shopping:product_detail', args=[self.slug, ])

    def update_quantity(self, sold_quantity):
        self.quantity -= sold_quantity
        if self.quantity > 0:
            self.available = True
        else:
            self.available = False
        self.save()

shopping/views.py
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.shortcuts import render, get_object_or_404

from cart.forms import CartAddForm
from .models import Product, Category


def home(request, slug=None):
    products = Product.objects.all()
    categories = Category.objects.filter(is_sub=False)
    if slug is not None:
        category = get_object_or_404(Category, slug=slug)
        products = products.filter(category=category)

    page = request.GET.get('page', 1)
    product_paginator = Paginator(products, 3)
    try:
        products_paginated = product_paginator.page(page)
    except PageNotAnInteger:
        products_paginated = product_paginator.page(1)
    except EmptyPage:
        products_paginated = product_paginator.page(product_paginator.num_pages)
    context = {
        'products': products_paginated,
        'categories': categories
    }
    return render(request, 'shopping/home.html', context=context)


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    form = CartAddForm(product=product)
    context = {
        'product': product,
        'form': form
    }
    return render(request, 'shopping/product_detail.html', context=context)

shopping/templates/shopping/home.html
{% extends 'layout.html' %}
{% load thumbnail %}

{% block content%}
    {% for category in categories %}
        <div class="btn-group mb-2" style="direction: ltr;">
            <a href="{{ category.get_absolute_url }}" class="btn btn-dark">{{ category.name }}</a>
            <button type="button" class="btn btn-dark dropdown-toggle dropdown-toggle-split" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
            <div class="dropdown-menu dropdown-menu-left">
                {% for sub in category.subcategory.all %}
                    <a class="dropdown-item" href="{{ sub.get_absolute_url }}">{{ sub.name }}</a>
                {% endfor %}
            </div>
        </div>
    {% endfor %}

    <br/><br/><br/>

    {% for product in products %}
        <div class="card border-dark pt-3 ml-3 mr-3 mt-3" style="width: 18rem; display:inline-block">
            {% thumbnail product.image "300x300" as img %}
                <img src="{{ img.url }}" class="card-img-top pl-3 pr-3" width="150px" height="300px">
            {% endthumbnail %}
            <div class="card-body">
                <a href="{{ product.get_absolute_url }}" class="card-title text-dark"> <hr>{{ product.name }}</a>
            </div>
        </div>
    {% endfor %}

    <br><br>

    {% if products.has_other_pages %}
        <nav aria-label="Page navigation example">
            <ul class="pagination" style="justify-content: center;">
                {% if products.has_previous %}
                        <li class="page-item ml-2"><a class="page-link text-dark rounded-bottom rounded-top" href="?page={{ products.previous_page_number }}">قبلی</a></li>
                {% else %}
                    <li class="disabled page-item ml-2" ><a class="page-link text-dark rounded-bottom rounded-top" href="">قبلی</a></li>
                {% endif %}
                {% for i in products.paginator.page_range %}
                    {% if products.number == i %}
                        <li class="disabled page-item"><span class="disabled page-link bg-dark text-light">{{ i }}</span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link text-dark" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if products.has_next %}
                    <li class="page-item mr-2"><a class="page-link text-dark rounded-bottom rounded-top" href="?page={{ products.next_page_number }}">بعدی</a></li>
                {% else %}
                    <li class="disabled page-item mr-2" ><a class="page-link text-dark rounded-bottom rounded-top" href="">بعدی</a></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}

shopping/templates/shopping/product_detail.html
{% extends 'layout.html' %}

{% block content %}
    <h3>{{ product.name }}</h3>
    <small>{{ product.created }}</small><p>{{ product.price }} تومان</p><br/>
    <img src="{{ product.image.url }}" alt="" width="400px" height="400px">
    <p>{{ product.description }}</p>

    <br/><br/>
    {% if product.available %}
        <form action="{% url 'cart:cart_add' product.id %}" method="post">
            {% csrf_token %}
            {% for error in form.quantity.errors %}
                <p class="alert alert-info col-6">{{ error }}</p>
            {% endfor %}
            <label for="{{ form.quantity.id_for_label }}">{{ form.quantity.label }}</label>
            {{ form.quantity }}
            <input type="submit" value="افزودن به سبد خرید">
        </form>
    {% else %}
        <p class="alert alert-warning col-6">موجودی این محصول به اتمام رسیده است</p>
    {% endif %}
{% endblock %}