accounts/urls.py
from django.urls import path,include


from . import views
from . import api_view

app_name = 'accounts'
urlpatterns = [
	path('login/', views.user_login, name='login'),
	path('logout/', views.user_logout, name='logout'),
	path('register/', views.user_register, name='register'),
	path('api/register',api_view.CreateUserAPIView.as_view(),name= 'api-register' ),
	path('api/activate',api_view.Activate.as_view(),name= 'api-activate' ),
	path('api/changepassword',api_view.ChangePassword.as_view(),name= 'api-change_password' ),
	path('api/resetpassword',api_view.ResetPassword.as_view(),name= 'api-reset_password' ),
	path('api/resetpasswordconfirm',api_view.ResetPasswordConfirm.as_view(),name= 'api-reset_password_confirm' ),
]

cart/urls.py
from django.urls import path, include

from . import views

app_name = 'cart'
urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
    path('api/', include('cart.api_urls'))
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'
urlpatterns = [
    path('create/', views.order_create, name='order-create'),
    path('detail/<int:order_id>/', views.order_detail, name='order-detail'),
    path('list/', views.order_list, name='order-list'),
    path('<int:order_id>/', views.order_finalize, name='order-finalize'),
    path('payment/<int:order_id>/<price>/', views.payment, name='order-payment'),
    path('verify/', views.verify, name='order-verify'),
    path('apply/<int:order_id>/', views.coupon_apply, name='order-coupon-apply'),
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from rest_framework_simplejwt import views as jwt_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('cart/', include('cart.urls')),
    path('oders/', include('orders.urls')),
    path('', include('shopping.urls')),
    path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),

]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shopping/urls.py
from django.urls import path, re_path, include

from . import views

from .api_url import router


app_name = 'shopping'
urlpatterns = [
	path('', views.home, name='home'),
	re_path(r'category/(?P<slug>[-\w]+)/', views.home, name='category_filter'),
	re_path(r'detail/(?P<slug>[-\w]+)/', views.product_detail, name='product_detail'),
	path('api/',include(router.urls))
]

templates/_messages.html
{% if messages %}
    {% for msg in messages %}
        <p class="alert alert-{{ msg.tags }}">{{ msg }}</p>
    {% endfor %}
{% endif %}

templates/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'shopping:home' %}">فروشگاه آنلاین</a>
        <a class="nav-item nav-link btn-outline-warning" href={% url "cart:cart_detail" %}>
            <i class="fas fa-shopping-basket"></i>
            سبد خرید
        </a>
        {% if user.is_authenticated %}
            <div class="dropdown nav-item">
                <a class="btn btn-sm btn-primary dropdown-toggle mt-1" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fas fa-user"></i>
                    {{ user.get_full_name }}
                </a>
                <div class="dropdown-menu text-right" dir="rtl">
                    <a class="dropdown-item" href="{% url "accounts:detail" %}">
                        <i class="far fa-address-card"></i>
                        نمایه کاربری
                    </a>
                    <a class="dropdown-item" href="{% url "orders:order-list" %}">
                        <i class="fas fa-receipt"></i>
                        خریدهای من
                    </a>
                    <a class="dropdown-item" href="{% url 'accounts:logout' %}">
                        <i class="fas fa-sign-out-alt"></i>
                        خروج
                    </a>
                </div>
            </div>
        {% else %}
            <a class="nav-item nav-link" href="{% url 'accounts:login' %}">ورود</a>
            <a class="nav-item nav-link" href="{% url 'accounts:register' %}">ثبت‌نام</a>
        {% endif %}
    </div>
</nav>

templates/layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% comment %} {% block extra_headers %}{% endblock %} {% endcomment %}
    <link rel="stylesheet" type="text/css" href="{% static "css/bootstrap.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/font-awesome.css" %}">
    <link rel="stylesheet" type="text/css" href="{% static "css/main.css" %}">
    {% block extra_css %}{% endblock %}
</head>
<body>

    {% include './_navbar.html' %}

    <div class="jumbotron">
        {% include './_messages.html' %}

        {% block content %}{% endblock %}
    </div>

    <footer id="sticky-footer" class="py-4 bg-dark text-white-50">
        <div class="container text-center">
            <small>
                <p>شبکه‌های اجتماعی ما</p>
            </small>
            <a class="social-media-icon text-white-50" href="https://facebook.com/#">
                <i class="fab fa-facebook"></i>
            </a>
            <a class="social-media-icon text-white-50" href="https://twitter.com/#">
                <i class="fab fa-twitter"></i>
            </a>
            <a class="social-media-icon text-white-50" href="https://instagram.com/#">
                <i class="fab fa-instagram"></i>
            </a>
            <a class="social-media-icon text-white-50" href="https://telegram.org/#">
                <i class="fab fa-telegram-plane"></i>
            </a>
        </div>
    </footer>

    <script src="{% static "js/jquery-3.4.0.min.js" %}"></script>
    <script src="{% static "js/bootstrap.bundle.js" %}"></script>
    <script src="{% static "js/font-awesome.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
    {% block extra_js %}{% endblock %}
</body>
</html>